server:
  port: 8080

#AWS credentials
aws:
  accessKey: *******
  secretKey: ********
  region: ********
  s3:
    bucket: *********

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB